CREATE TABLE section (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    dummy TEXT NOT NULL,
    created DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE stats (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    insert_section_count INTEGER NOT NULL DEFAULT 0,
    remove_section_count INTEGER NOT NULL DEFAULT 0,
    last_insert_section DATETIME NOT NULL DEFAULT 0,
    last_remove_section DATETIME NOT NULL DEFAULT 0
);

INSERT INTO stats (id) VALUES (1);

CREATE TABLE rows (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    section_id INTEGER NOT NULL REFERENCES section(id),
    random_float REAL,
    count_updates INTEGER NOT NULL DEFAULT 0,
    dummy TEXT NOT NULL,
    created DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated DATETIME DEFAULT CURRENT_TIMESTAMP
);

